# PocketPhoto v1.2.1
language: "ko"
use-map-sprite: true      # true면 Filled Map으로 스프라이트 렌더, 실패 시 PAPER로 자동 폴백
map-scale: 2              # 0~4
pokegive-slot-key: "s"    # CatServer/Pixelmon 9.1.x는 s: 권장 (서버가 slot:만 받으면 "slot"으로 교체)

photo-title-format: "§e[ 포켓 사진 ] §f%species% §7Lv %level%"
rich-lore: true
