# UltimatePokeItemizer - 기본 설정
bind-owner: true              # 아이템을 원 소유자에게만 소환 가능
allow-trade: false            # true면 다른 유저도 소환 가능(바인딩 무시)
consume-on-redeem: true       # 소환 시 아이템 1개 소비
require-empty-party-slot: true

# 중복 사용 방지: 한 번 소환된 토큰은 다시 사용 불가
duplicate-prevention: true

# 아이템 표시 (색코드는 & 사용)
item:
  material: BOOK
  custom-model-data: 0
  name: "&6[ {species-ko} ] &a{level} Lv"
  lore:
    - "&a닉네임&f : {nickname}"
    - "&d알까진정도&f : {hatch}"
    - "&c성격&f : {nature-ko}"
    - "&e특성&f : {ability}"
    - "&b기술&f : {moves}"
    - "&f개체값(IV) &7:&c {iv-hp}&7/&c{iv-atk}&7/&c{iv-def}&7/&c{iv-spa}&7/&c{iv-spd}&7/&c{iv-spe} &8({iv-sum}/186)"
    - "&f노력치(EV) &7:&3 {ev-hp}&7/&3{ev-atk}&7/&3{ev-def}&7/&3{ev-spa}&7/&3{ev-spd}&7/&3{ev-spe} &8({ev-sum}/510)"
    - "&f성별&7 : {gender-ko}  &f성장&7 : {growth-ko}  &f친밀도&7 : {friendship}"
    - "&7소유자 : {owner}"
