bind-owner: true
allow-trade: false
consume-on-redeem: true
require-empty-party-slot: true
duplicate-prevention: true

item:
  material: BOOK
  custom-model-data: 0
  name: "&6[ {species-ko} ] &a{level} Lv"
  lore:
    - "&a닉네임&f : {nickname}"
    - "&d알까진정도&f : {hatch}"
    - "&c성격&f : {nature-ko}"
    - "&e특성&f : {ability-clean}"
    - "&b기술&f : {moves-clean}"
    - "&f개체값(IV) &7:&c {iv-hp}&7/&c{iv-atk}&7/&c{iv-def}&7/&c{iv-spa}&7/&c{iv-spd}&7/&c{iv-spe} &8({iv-sum}/186)"
    - "&f노력치(EV) &7:&3 {ev-hp}&7/&3{ev-atk}&7/&3{ev-def}&7/&3{ev-spa}&7/&3{ev-spd}&7/&3{ev-spe} &8({ev-sum}/510)"
    - "&f성별&7 : {gender-ko}  &f성장&7 : {growth-ko}  &f친밀도&7 : {friendship}"
    - "&7소유자 : {owner}"
