name: PokeBagPhoto
main: com.example.pokebagphoto.PokeBagPhoto
version: 1.1.5
api-version: 1.16
commands:
  pb:
    description: Turn your Pixelmon party slot into a photo item.
    usage: /pb <1-6> [targetSlot]
permissions: {}
