name: PokeBagPhoto
main: com.example.pokebagphoto.PokeBagPhoto
version: 1.1.6
api-version: 1.16
commands:
  pb:
    description: Take Pixelmon party slot as a photo item and restore on use.
    usage: /pb <1-6> [targetSlot]
